### ISSUE TITLE
Any dependency?

### ISSUE THREAD

**Issue by rggit2019** [govert/SQLiteForExcel#10]
Hi, I am trying to run the test but I get Error 53 FIle not found SQLite3_Stdcall.dll"  Is there any dependency I am missing? I tried hard coding the dll directory but doesn't seem to help.

**Comment by beyphy** [comment]
Okay, after a decent chunk of investigation I figured out the "file not found" issue. It looks like by default, Excel sets the current directory to your local My Documents folder, _even if the Excel file isn't saved there_. You can test this yourself. Save the file somewhere other than your my documents folder. Then debug.print CurDir. It should print your local documents directory. So if you want to use these files you have two options: 

The simpler, more straightforward option is to just save the sqlite3 database to your local my documents folder. You may need to save the 64bit version if your system requires it. After you do that, the code in the files should work since the database will always be in the current directory (i.e. your  local my documents folder)

Another option is to run a procedure to change the current directory to the path of the activeworkbook. This can be done like so:

`Sub ChangeDir()
    ChDir ActiveWorkbook.Path
End Sub`

You only need to run this once for this to work. The biggest downside of this option is that you'll always need to manually run this code once. If this code were in a class module, I could just set this code in the constructor. But it isn't unfortunately. Perhaps I will update this project to use a class module.

**Comment by francogrex** [comment]
the SQLite3_Stdcall.dll should be in the path, as it is in the same directory as the demo, but somehow is not being called or is actually of the wrong format for win64

**Comment by govert** [comment]
@francogrex The sqlite3_stdcall.dll file is only used under 32-bit Excel (might be 32-bit or 64-bit Windows). For a 64-bit process there is only one calling convention, and this file is not used.
